name: 'download.pytorch.org schedule'

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:


jobs:
  job_0:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
              git gcc g++ make cmake ninja-build curl \
              libgl1 libglib2.0-0 libsndfile1

      # See: https://github.com/actions/checkout/issues/363#issuecomment-1915075699
      # See: https://github.com/hunshcn/gh-proxy/issues/28#issuecomment-773769630
      - name: Config git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
    
      - name: Install torch_npu dependencies
        run: |
          pip install -vvv -r https://raw.githubusercontent.com/Ascend/pytorch/refs/heads/master/requirements.txt
