name: arc-runner-set
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: arc-runner-set
    container:
      image: ubuntu:22.04

    steps:
      - name: Sleep
        run: |
          echo "hello"
          ls
