name: arc-runner-set
on:
  workflow_dispatch:


  # schedule:
  #   - cron: '*/1 * * * *' 

jobs:
  download:
    runs-on: arc-runner-set
    steps:
      - name: Sleep
        run: |
          echo "hello"
          ls
