name: 'ci failed'

on:
  workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job2:
    name: job2
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job3:
    name: job3
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job4:
    name: job4
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job5:
    name: job5
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job6:
    name: job6
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job7:
    name: job7
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job8:
    name: job8
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
  job9:
    name: job9
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600
