name: Hidevlab_single
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: hidevlab-npu-1
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/openeuler:24.03-arm

    steps:
      - name: Sleep
        run: npu-smi info
