name: 'pod2-3'

on:
  workflow_dispatch:


jobs:
  job1:
    name: job1
    runs-on: linux-arm64-npu-4
    container:
      image: ascendai/cann:latest
    steps:
      - run: npu-smi info
      - run: sleep 3600


