name: Buildah
on:
  workflow_dispatch:
jobs:
  job_0:
    runs-on: linux-arm64-npu-1
    container:
      image: dodok0a/stable:latest # dodok0a/stable:latest是将quay.io/buildah/stable:latest存储到dockerhub
      
    steps:
      - run: sleep 3600
