name: Publish Image from GHCR to Docker Hub

on:
  workflow_call:
    secrets:
      origin_registry:
        required: true
        # type: string
        description: 'Origin registry'
      origin_username:
        required: true
        # type: string
        description: 'Origin username'
      origin_password:
        required: true
        # type: string
        description: 'Origin password'
      target_registry:
        required: true
        # type: string
        description: 'Target registry'
      target_username:
        required: true
        # type: string
        description: 'Target username'
      target_password:
        required: true
        # type: string
        description: 'Target password'
      image_name:
        required: true
        # type: string
        description: 'Image name'
      image_tag:
        required: true
        # type: string
        description: 'Image tag'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Origin Repository
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.origin_registry }}
          username: ${{ secrets.origin_username }}
          password: ${{ secrets.origin_password }}

      - name: Login to Target Repository
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.target_registry }}
          username: ${{ secrets.target_username }}
          password: ${{ secrets.target_password }}

      - name: Pull image
        run: docker pull ${{ secrets.origin_registry }}/${{ secrets.origin_username }}/${{ secrets.image_name }}:${{ secrets.image_name }}

      - name: Tag image
        run: docker tag ${{ secrets.origin_registry }}/${{ github.actor }}/${{ secrets.image_name }}:${{ secrets.image_name }} ${{ secrets.target_username }}/${{ secrets.image_name }}:${{ secrets.image_name }}

      - name: Push image
        run: docker push ${{ secrets.target_username }}/${{ secrets.image_name }}:${{ secrets.image_name }}