name: test_aicc_runner_scheduler
on:
  workflow_dispatch:
jobs:
  scheduler:
    strategy:
      matrix:
        param: [p1, p2, p3, p4, p5, p6, p7, p8]
    runs-on: aicc-linux-arm64-npu-1
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          npu-smi info
