name: Test NPU 1, 2, 4, 8
on:
  workflow_dispatch:
jobs:
  job_0:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: cd /shared-data
      - run: apt update -y
      - run: apt install -y git
      - run: git clone https://gh-proxy.test.osinfra.cn/https://github.com/opensourceways/BigFiles

  job_1:
    runs-on: linux-arm64-npu-2
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
      - run: ls /shared-data/BigFiles

  job_2:
    runs-on: linux-arm64-npu-4
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
      - run: ls /shared-data/BigFiles

  job_3:
    runs-on: linux-arm64-npu-8
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
      - run: ls /shared-data/BigFiles
