name: test_git
on:
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: aicc-linux-arm64-npu-1
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          # if [[ "${{ matrix.os }}" == "linux-arm64-npu-1" ]]; then
          #   npu-smi info
          # else
          #   echo "hello"
          # fi
          echo "配置代理："
          cat ~/.gitconfig

          echo "代理网络通畅:"
          apt update -y
          apt install git -y
          git clone https://gh-proxy.test.osinfra.cn/https://github.com/actions/actions-runner-controller
          
          sleep 3600
