name: Test NPU 1, 2, 4, 8
on:
  workflow_dispatch:
jobs:
  job_3:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: cd /shared-data
      - run: sleep 3600
      - run: git clone https://github.com/actions/runner-container-hooks
  job_4:
    runs-on: linux-arm64-npu-2
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
    
  job_5:
    runs-on: linux-arm64-npu-4
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
      - run: ls /shared-data/runner-container-hooks/

  job_6:
    runs-on: linux-arm64-npu-8
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
      - run: ls /shared-data/runner-container-hooks/
