name: test_git
on:
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: aicc-linux-arm64-npu-1
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          apt update -y
          apt install git -y

          npu-smi info
          echo "完成配置代理： cat ~/.gitconfig"
          cat ~/.gitconfig

          echo "代理网络通畅: git clone https://gh-proxy.test.osinfra.cn/https://github.com/actions/actions-runner-controller"
          
          git clone https://gh-proxy.test.osinfra.cn/https://github.com/actions/actions-runner-controller
          ls
          
          sleep 3600
