name: test_aicc_runner_scheduler
on:
  workflow_dispatch:
jobs:
  scheduler:
    strategy:
      matrix:
        os: [linux-arm64-npu-0, linux-arm64-npu-1, linux-arm64-npu-2, linux-arm64-npu-4]
        param: [p1, p2, p3]
    runs-on: ${{ matrix.os }}
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          if [[ "${{ matrix.os }}" == "linux-arm64-npu-1" ]]; then
            npu-smi info
          else
            echo "hello"
          fi
          sleep 10
