name: Test NPU 1, 2, 4, 8
on:
  workflow_dispatch:
jobs:
  job_3:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 3600
  job_4:
    runs-on: linux-arm64-npu-2
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 3600
  job_5:
    runs-on: linux-arm64-npu-4
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 3600
