name: test_new_pod
on:
  workflow_dispatch:

jobs:
  download:
    strategy:
      max-parallel: 4
      matrix:
        os: [linux-arm64-npu-2, linux-arm64-npu-4]
        vllm_verison: [main, v0.8.5.post1]
    runs-on: ${{ matrix.os }}
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          npu-smi info
          sleep 3600
