name: Test Concurrency Error 2
on:
  workflow_dispatch:
jobs:
  job_0:
    runs-on: vllm
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

  job_1:
    runs-on: vllm
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
