name: Test NPU 1, 2, 4, 8
on:
  workflow_dispatch:
jobs:
  job_3:
    runs-on: linux-arm64-npu-8
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
