name: test_shceduler
on:
  workflow_dispatch:

jobs:
  download:
    strategy:
      max-parallel: 8
      matrix:
        a: [v1, v2, v3]
        b: [b1, b2, b3]
    runs-on: linux-arm64-npu-4
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10

    steps:
      - name: Sleep
        run: |
          npu-smi info
          sleep 3600
